# Generated by Django 2.2 on 2019-12-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
